/*
 * This program is generated by HMGCASE
 * developed by Dragan Cizmarevic < dragancesu(at)gmail.com > 
 */

#include <hmg.ch>

PROCEDURE MAIN 

   set century on
   set date german
   set interactiveclose on
   set multiple off warning
   set navigation extended
   set tooltipstyle balloon

   SET FONT TO 'MS Shell Dlg', 8

   DEFINE WINDOW MainForm ;
      AT 10, 10 ;
      WIDTH 800 ; 
      HEIGHT 600 ; 
      TITLE "mini control wizard" ;
      ICON "main.ico" ;
      MAIN

      ON KEY ESCAPE ACTION MainForm.Release

   @ 100, 100 BUTTON butt_2246_A ; 
      CAPTION " BROWSE " ; 
      ACTION brow_wizz() ; 
      WIDTH 150 ; 
      HEIGHT 70 ;
      TOOLTIP 'Start browse wizard'

   @ 100, 300 BUTTON butt_2246_B ; 
      CAPTION " BUTTON " ; 
      ACTION butt_wizz() ; 
      WIDTH 150 ; 
      HEIGHT 70 ;
      TOOLTIP 'Start button wizard'

   @ 100, 500 BUTTON butt_2246_C ; 
      CAPTION " CHECKBOX " ; 
      ACTION chkb_wizz() ; 
      WIDTH 150 ; 
      HEIGHT 70 ;
      TOOLTIP 'Start checkbox wizard'

   @ 200, 100 BUTTON butt_2246_D ; 
      CAPTION " RADIOGROUP " ; 
      ACTION radio_wizz() ; 
      WIDTH 150 ; 
      HEIGHT 70 ;
      TOOLTIP 'Start radiogroup wizard'

   @ 200, 300 BUTTON butt_2246_E ; 
      CAPTION " TOOLBAR " ; 
      ACTION tool_wizz() ; 
      WIDTH 150 ; 
      HEIGHT 70 ;
      TOOLTIP 'Start toolbar wizard'

   @ 200, 500 BUTTON butt_2246_F ; 
      CAPTION " LAUNCH test.prg " ; 
      ACTION run_test() ; 
      WIDTH 150 ; 
      HEIGHT 70 ;
      TOOLTIP 'Start test app'

   END WINDOW
   
   CENTER WINDOW MainForm

   ACTIVATE WINDOW MainForm

RETURN


PROCEDURE run_test()

   ShellExecute( 0, "open", "compile.bat", , , 1 ) 

RETURN
