/*
 * This program is generated by HMGCASE
 * developed by Dragan Cizmarevic < dragancesu(at)gmail.com > 
 */

#include <hmg.ch>

PROCEDURE apl_mnus

   PUBLIC NewRec := .F., EditRec := .F.,  FindRec := .F., FiltRec := .F., _qry_exp := ""

   open_mnu()
   use _aplmnus index _aplmnus new

   DEFINE WINDOW Win_1 ;
      AT 0,0 ;
      WIDTH 1000 ;
      HEIGHT 700 ;
      TITLE "Aplication menus/submenus" ;
      MODAL ;
      ON RELEASE re_order_mnus() ;
      BACKCOLOR { 230, 230, 230 }

      ON KEY ESCAPE ACTION CancelEdit_0862() 

      ON KEY F4   ACTION ( FiltRec := .F., EditRec := .T., NewRec := .F., If ( RecordStatus_0862(), EnableField_0862(), Nil ))
      ON KEY F6   ACTION ( FiltRec := .F., NewRec := .T., EditRec = .F., NewRecord_0862() )
      ON KEY F8   ACTION ( FiltRec := .F., RecordStatus_0862(), DeleteRecord_0862(), Nil )
      ON KEY F10  ACTION Win_1.Release

      DEFINE STATUSBAR FONT "Arial" SIZE 12
         STATUSITEM "Table submenu"
      END STATUSBAR

      DEFINE TOOLBAR ToolBar_1 BUTTONSIZE 50,50 IMAGESIZE 24,24 FLAT BORDER

      BUTTON EDIT_0862 ;
         CAPTION "[F4] Edit" ;
         PICTURE "edit_edit" ;
         ACTION ( FiltRec := .F., EditRec := .T., NewRec := .F., If ( RecordStatus_0862(), EnableField_0862(), Nil ))

      BUTTON NEW_0862 ;
         CAPTION "[F6] New" ;
         PICTURE "edit_new" ;
         ACTION ( FiltRec := .F., NewRec := .T., EditRec = .F., NewRecord_0862() )

      BUTTON DELETE_0862 ;
         CAPTION "[F8] Delete" ;
         PICTURE "edit_delete" ;
         ACTION ( FiltRec := .F., RecordStatus_0862(), DeleteRecord_0862(), Nil )

      BUTTON EXIT_0862 ;
         CAPTION "[F10] Exit" ;
         PICTURE "edit_close" ;
         ACTION Win_1.Release

      END TOOLBAR

      PaintDisplay_0862()

      @ 90, 10 BROWSE Browse_1 ;
         OF Win_1 ;
         WIDTH 750 ;
         HEIGHT 300 ;
         FONT "Arial" ; 
         SIZE 10 ;
         HEADERS { "(3)","NO","ITEM","ACTION","MODUL" } ;
         WIDTHS { 50,50,250,180,180 } ;
         WORKAREA _APLMNUS ;
         FIELDS { "LEVEL3","LEVEL4","ITEM","ACTION","MODUL" } ;
         ON CHANGE LoadData_0862() ;
         ON DBLCLICK ( EnableField_0862(), If ( ! RecordStatus_0862(), DisableField_0862(), Nil ) ) ;
         JUSTIFY { BROWSE_JTFY_RIGHT, BROWSE_JTFY_RIGHT, , , , } 

      @ 580, 50 BUTTON SAVE_0862 ;
         CAPTION "Save" ;
         PICTURE "ok" RIGHT ;
         ACTION SaveRecord_0862() ;
         WIDTH 100 ;
         HEIGHT 40 

      @ 580, 150 BUTTON CANCEL_0862 ;
         CAPTION "Cancel" ;
         PICTURE "cancel" RIGHT ;
         ACTION CancelEdit_0862() ;
         WIDTH 100 ;
         HEIGHT 40 

   END WINDOW

   DisableField_0862()

   Win_1.Browse_1.SetFocus
   Win_1.Browse_1.Value := _APLMNUS->(RecNo())

   ACTIVATE WINDOW Win_1

RETURN
*:---------------------------------------------*
PROCEDURE DisableField_0862

   Win_1.Browse_1.Enabled      := .T.

   Win_1.mLEVEL3.Enabled       := .F.
   Win_1.mLEVEL4.Enabled       := .F.
   Win_1.mITEM.Enabled         := .F.
   Win_1.mACTION.Enabled       := .F.
   Win_1.mMODUL.Enabled        := .F.

   Win_1.Save_0862.Enabled     := .F.
   Win_1.Cancel_0862.Enabled   := .F.
   Win_1.Toolbar_1.Enabled     := .T.
   Win_1.Browse_1.SetFocus

RETURN
*:---------------------------------------------*
PROCEDURE EnableField_0862

   Win_1.Browse_1.Enabled      := .F.

   Win_1.mLEVEL3.Enabled       := .T.
   Win_1.mLEVEL4.Enabled       := .T.
   Win_1.mITEM.Enabled         := .T.
   Win_1.mACTION.Enabled       := .T.
   Win_1.mMODUL.Enabled        := .T.

   Win_1.Save_0862.Enabled     := .T.
   Win_1.Cancel_0862.Enabled   := .T.
   Win_1.Toolbar_1.Enabled     := .F.
   Win_1.mLEVEL4.SetFocus

RETURN
*:---------------------------------------------*
FUNCTION RecordStatus_0862()

   Local RetVal

   _APLMNUS->( dbGoTo ( Win_1.Browse_1.Value ) )

   IF _APLMNUS->(RLock())
      RetVal := .T.
   ELSE
      MsgExclamation ("Record LOCKED, try again later")
      RetVal := .F.
   ENDIF

RETURN RetVal
*:---------------------------------------------*
PROCEDURE LoadData_0862

   _APLMNUS->( dbGoTo ( Win_1.Browse_1.Value ) )

   Win_1.mLEVEL3.Value       := _APLMNUS->LEVEL3    
   Win_1.mLEVEL4.Value       := _APLMNUS->LEVEL4    
   Win_1.mITEM.Value         := _APLMNUS->ITEM      
   Win_1.mACTION.Value       := _APLMNUS->ACTION    
   Win_1.mMODUL.Value        := _APLMNUS->MODUL     

RETURN
*:---------------------------------------------*
PROCEDURE CancelEdit_0862

   DisableField_0862()
   LoadData_0862()
   UNLOCK
   NewRec := .F.
   Win_1.Browse_1.SetFocus

RETURN
*:---------------------------------------------*
PROCEDURE SaveRecord_0862

   Local NewRecNo

   DisableField_0862()

   IF NewRec == .T.
      _APLMNUS->(dbAppend())
      NewRec := .F.
   ELSE
      _APLMNUS->(dbGoto ( Win_1.Browse_1.Value ) )
   ENDIF

   NewRecNo := _APLMNUS->( RecNo() )

   _APLMNUS->LEVEL3     := Win_1.mLEVEL3.Value
   _APLMNUS->LEVEL4     := Win_1.mLEVEL4.Value
   _APLMNUS->ITEM       := Win_1.mITEM.Value
   _APLMNUS->ACTION     := Win_1.mACTION.Value
   _APLMNUS->MODUL      := Win_1.mMODUL.Value

   Win_1.Browse_1.Refresh
   IF NewRec == .T.
      Win_1.Browse_1.Value := NewRecNo 
   ENDIF

   UNLOCK
   dbCommitall()

   Win_1.StatusBar.Item(1) := "Save Record" 

RETURN
*:---------------------------------------------*
PROCEDURE NewRecord_0862

   Win_1.StatusBar.Item(1) := "Inserting" 

   SET ORDER TO 1
   *dbGoBottom()

   Win_1.mLEVEL3.Value       := level3
   Win_1.mLEVEL4.Value       := level4+1
   Win_1.mITEM.Value         := "."
   Win_1.mACTION.Value       := "nil"
   Win_1.mMODUL.Value        := space(10)

   EnableField_0862()

   Win_1.mLEVEL3.SetFocus

RETURN
*:---------------------------------------------*
PROCEDURE DeleteRecord_0862

   IF MsgYesNo ( "Are you sure do you want delete record?" )
      IF _APLMNUS->(FLock())
         DELETE
         Win_1.Browse_1.Refresh
         UNLOCK
      ENDIF
   ENDIF

RETURN
*:---------------------------------------------*
PROCEDURE PaintDisplay_0862

   @ 400,  20 LABEL Label_1 VALUE "(3)" TRANSPARENT 
   @ 400,  65 LABEL Label_2 VALUE "NO" TRANSPARENT 
   @ 400, 100 LABEL Label_3 VALUE "ITEM" TRANSPARENT 
   @ 400, 360 LABEL Label_4 VALUE "ACTION" TRANSPARENT 
   @ 400, 540 LABEL Label_5 VALUE "MODUL" TRANSPARENT 

   @ 420,  20 TEXTBOX  mLEVEL3      WIDTH 35 NUMERIC INPUTMASK "999"
   @ 420,  65 TEXTBOX  mLEVEL4      WIDTH 25 NUMERIC INPUTMASK "99"
   @ 420, 100 TEXTBOX  mITEM        WIDTH 250
   @ 420, 360 TEXTBOX  mACTION      WIDTH 170 
   @ 420, 540 TEXTBOX  mMODUL       WIDTH 170 

RETURN
*:---------------------------------------------*
FUNCTION re_order_mnus ()

use _aplmnus index _aplmnus
pack
copy to _work

dbcloseall()

select 2
use _aplmnus index _aplmnus
zap

select 1
use _work 
index on str(level3,3)+str(level4,2) to _work

_lvl3 = level3
_lvl4 = 0

*** level 0 ***

do while .not. eof()

   _level3 = level3
   _level4 = level4
   _item   = item
   _action = action
   _modul = modul
   
   if _Lvl3 != _level3
      _lvl4 = 0
   endif  
      
   _lvl4++

   select 2
   dbappend()
   replace level3 with _level3
   replace level4 with _lvl4
   replace item with _item
   replace action with _action
   replace modul with _modul

   select 1
   _lvl3 = level3
   
   dbskip()
enddo

dbcloseall()

delete file _work.dbf
delete file _work.ntx

return
