#
# use: JoseQuintas/addons/mingw_0703
# use: JoseQuintas/addons/hb34_0703

name: hb34pack

on:
#  push:
  schedule:
   - cron: "45 5 2 * *"
  workflow_dispatch:
    inputs:
      name:
        description: 'hb34pack'
        default: 'hb34pack'
        required: true

jobs:

  Build:
    runs-on: windows-latest
    steps:

    - name: mingw 7.3
      uses: JoseQuintas/action-download-artifact@v2
      with:
         workflow: mingw_0703.yml
         workflow_conclusion: success
         name: mingw_0703
         path: c:\temp
         repo: JoseQuintas/addons

    - name: harbour 3.4
      uses: JoseQuintas/action-download-artifact@v2
      with:
         workflow: hb34_0703.yml
         workflow_conclusion: success
         name: hb34_0703
         path: c:\temp
         repo: JoseQuintas/addons

    - name: Unzip
      env:
         PATH: c:\program files\7-zip
      run: |
         c:
         7z x -y c:\temp\hb34_0703.7z -oc:\temp\harbour
         7z x -y c:\temp\mingw_0703.7z -oc:\temp\mingw

    - name: Load Source Code
      env:
         REPO: JoseQuintas/addons
      run: |
         c:
         git clone https://github.com/$env:repo c:\temp\harbour\addons --depth 1
         git clone https://github.com/JoseQuintas/hwgui c:\temp\harbour\addons\hwgui
         git clone https://github.com/JoseQuintas/sefazclass c:\temp\harbour\addons\sefazclass
         git clone https://github.com/JoseQuintas/wvgtst c:\temp\harbour\addons\wvgtst

    - name: Build All
      env:
         HB_BUILD_STRIP: all
         HB_COMPILER: mingw
         HB_INSTALL_PREFIX: c:\temp\harbour
         HBMK_CMD: -workdir=c:\temp -q -quiet
         PATH: c:\temp\mingw\mingw64\bin;c:\temp\harbour\bin
      run: |
         c:
         cd c:\temp\harbour\addons\hwgui
         hbmk2 hwgui.hbp
         hbmk2 hwgui.hbp -comp=mingw64

         cd c:\temp\harbour\addons\deleted_hb
         hbmk2 deleted_hb.hbp
         hbmk2 deleted_hb.hbp -comp=mingw64

         cd c:\temp\harbour\addons\sefazclass
         hbmk2 sefazclass.hbp
         hbmk2 sefazclass.hbp  -comp=mingw64

         cd c:\temp\harbour\addons\hmg3
         hbmk2 hmg3.hbp -workdir=c:\temp -quiet
         hbmk2 hmg3.hbp -workdir=c:\temp -comp=mingw64 -quiet

         cd c:\temp\harbour\addons\wvgtst
         hbmk2 wvgtst.hbp
         hbmk2 wvgtst.hbp -comp=mingw64

    - name: Zip
      env:
         PATH: c:\program files\7-zip
      run: |
         c:
         7z a -r c:\temp\hb34pack.7z c:\temp\harbour\*.* -xr'!.git' -xr'!.github' -xr'!.hbmk'

    - name: Save
      uses: actions/upload-artifact@v2
      with:
         name: harbour
         path: c:\temp\hb34pack.7z

